services:
  db:
    image: postgres:16
    restart: always
    environment:
      - PGDATABASE=${DATABASE_DB}
      - PGUSER=${DATABASE_USER}
      - PGPASSWORD=${DATABASE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Postgres' standard port
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

  # React client frontend
  frontend:
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend:/usr/src
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:3000

  # Backend Rails API
  backend:
    restart: always
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "3001:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: