services:
  db:
    image: postgres:16
    restart: always
    environment:
      - PGDATABASE=${DATABASE_DB}
      - PGUSER=${DATABASE_USER}
      - PGPASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_DB}
    ports:
      - "5432" # Postgres' standard port
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

  # Backend Rails API
  backend:
    restart: always
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "3001:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
